### ISSUE TITLE
No Config

### ISSUE THREAD

**Issue by LamboCreeper** [HogwartsMC/staffchatbungee#1]
Hi,

I recently downloaded your Bungee plugin and I see no config for it, I can reload it using /screload and still no config. Any reason for this?

**Comment by Jake-SA** [comment]
Hey there, are there any errors in the startup log immediately after trying to run it? Check in the "logs/" folder for "latest.log" and paste a link to a pasting site (pastebin, hastebin) of that here.

Secondly, what version of Bungee and what version of StaffChatBungee?

I presume something is going wrong early on if there is no configuration generated. You say there is no "StaffChatBungee" data folder created in "plugins/" when the plugin starts?

**Comment by LamboCreeper** [comment]
I have the plugin config now. I forgot to refresh my FPT

**Comment by Jake-SA** [comment]
@LamboCreeper Ok, good to here.
