### ISSUE TITLE
Add RedisBungee support

### ISSUE THREAD

**Issue by Jake-SA** [HogwartsMC/staffchatbungee#2]
Modify code to allow usage of RedisBungee in order to accommodate multiple Bungees.

**Comment by Jake-SA** [comment]
Working on branch v2.0.0.

**Comment by Jake-SA** [comment]
Done -> moved to new private repo

**Comment by Time6628** [comment]
Is 2.0.0 available yet?

**Comment by Jake-SA** [comment]
@Time6628 It's in the pro version of this plugin -- see Spigot resources section "Staff Chat Bungee Pro".
$3 and you get RedisBungee support and more.
